spring:
  profiles:
    active:
      - dev
---

spring:
  profiles: dev  #开发环境
  application:
    name: microservice-config-wang-dev

---
spring:
  profiles: test  #测试环境
  application:
    name: microservice-config-wang-test